### ISSUE TITLE
Unduly specific name?

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/elm-price-chart#11]
This is really nice!

I wonder if the name isn't too specific. Seems chart could have many applications beyond finance.

**Comment by abingham** [comment]
My vision right now is that this module will consist of charts specific to finance, something like [TechanJS](http://techanjs.org/). Over time I'm sure generic parts of it should be migrated into their own modules (or perhaps into elm-visualization, upon which we rely). But the "important" parts of this module, like candlesticks, are, as far as I know, only or primarily used for finance.

Maybe the Elm charting ecosystem will evolve to the point where these charts would more naturally be part of some larger project. For now, though, this seems like the most logical arrangement.

**Comment by rob-smallshire** [comment]
Fair enough. Strong vision is important!
